// ============================================================
// FILE: lib/models/stock.dart
// PURPOSE: Defines what a Stock looks like (like a table row in DB)
// ============================================================
import 'package:flutter/material.dart';
class Stock {
  final int? id;          // Auto-generated by database
  final String name;      // e.g. "TechCorp"
  final String ticker;    // e.g. "TCC"
  final double price;     // e.g. 150.25
  final double change;    // e.g. 12.5 (percentage)
  final String riskLevel; // "Low", "Medium", or "High"
  final String status;    // e.g. "Stable growth"
  final bool isInWatchlist;

  Stock({
    this.id,
    required this.name,
    required this.ticker,
    required this.price,
    required this.change,
    required this.riskLevel,
    required this.status,
    this.isInWatchlist = false,
  });

  // Convert a Stock into a Map (for saving to database)
  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'name': name,
      'ticker': ticker,
      'price': price,
      'change': change,
      'riskLevel': riskLevel,
      'status': status,
      'isInWatchlist': isInWatchlist ? 1 : 0, // SQLite uses 1/0 for true/false
    };
  }

  // Convert a Map (from database) back into a Stock object
  factory Stock.fromMap(Map<String, dynamic> map) {
    return Stock(
      id: map['id'],
      name: map['name'],
      ticker: map['ticker'],
      price: map['price'],
      change: map['change'],
      riskLevel: map['riskLevel'],
      status: map['status'],
      isInWatchlist: map['isInWatchlist'] == 1,
    );
  }
}
